### ISSUE TITLE
SSL support in Geiss

### ISSUE THREAD

**Issue by alexeykuzub** [ostcar/goasgiserver#7]
Hello! I tried Geiss with Django-channels and It is very good for me. But I need to use it over SSL. Is there some way to do it?

**Comment by matthiask** [comment]
I put geiss behind nginx for a production deployment. This works well.

**Comment by alexeykuzub** [comment]
Oh, sorry that the information is incomplete. I need to use IIS and I need to run Geiss for websockets alongside IIS. With Daphne It works. I want to plug in SSL with Geiss to use wss instead ws protocol. When I run Daphne I specify the parameters privateKey and extraCertChain. I need to know, Is there something like this in Geiss?

**Comment by ostcar** [comment]
Currently ssl is not supported. It could be implemented by I have no time at the moment to do it.

It should be possible by replacing in [this](https://github.com/ostcar/geiss/blob/bb3010ede4c62a012be7022a29d99826cdb7f654/server.go#L56) line the function with [ListenAndServeTLS](https://golang.org/pkg/net/http/#ListenAndServeTLS)

But I did not work with go and ssl before. It seems simple.

**Comment by alexeykuzub** [comment]
Thank you! Can you tell me, how many connections Geiss can handle without errors?

**Comment by ostcar** [comment]
I stop supporting geiss. To support channels 2, it would have to interpret python. To use channels 2, please use something else like uvicorn
